# Generated by Django 2.2.3 on 2019-08-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='ost_id',
            new_name='post_id',
        ),
    ]
