# Generated by Django 2.2.4 on 2019-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20190810_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istuser',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
